### PR TITLE
git subrepo pull (merge) low_disk

### PR DESCRIPTION
**Pull request by LukeShirnia**
Testing: 
https://github.com/LukeShirnia/Low_Disk/pull/7
https://github.com/LukeShirnia/Low_Disk/pull/8
```
subrepo:
  subdir:   "low_disk"
  merged:   "ab76b0f"
upstream:
  origin:   "https://github.com/LukeShirnia/Low_Disk.git"
  branch:   "master"
  commit:   "ab76b0f"
git-subrepo:
  version:  "0.4.1"
  origin:   "https://github.com/ingydotnet/git-subrepo"
  commit:   "a04d8c2"
```
```
$ ./audit.sh --update low_disk

------------------------------------------
Verifying recorded commit...

Commit on file: e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5
https://raw.githubusercontent.com/rackerlabs/useful-scripts/master/low_disk/.gitrepo

Remote Repo Info (commit)
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

SubRepo (remote) Info (master)
https://raw.githubusercontent.com/rackerlabs/useful-scripts/master/low_disk/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

Verifying commit: sha1sums match!
master (remote branch) is inline with specified commit hash
------------------------------------------

------------------------------------------
Checking if updates available... (script/commit vs script/master)

Remote 'Commit' URL
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

Remote 'Master' URL
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/master/disk_usage_check.sh
sha1sum: 3cde181f47ec38652f9c8d9fc84bcd27b266ed8f

Master and commit hash do NOT match
Updates: Possible updates available

Compare URL:
https://github.com/LukeShirnia/Low_Disk/compare/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5...master

------------------------------------------


Error: You appear to be working on the master branch!
Updating/adding should be added to a sub branch.

Would you like to autocreate a new branch (low_disk-update-2020-09-11)? (y|n) y
Branch Updated.....
Verifying Update.....
Cleaning up....
Deleted branch subrepo/low_disk (was ab76b0f).

------------------------------------------
Verifying recorded commit...

Commit on file: ab76b0f947ded33b84c95e3b5efb3f82146fa3e7
/home/lukeshirnia/development/github/git_rackspace/useful-scripts/low_disk/.gitrepo

Remote Repo Info (commit)
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/ab76b0f947ded33b84c95e3b5efb3f82146fa3e7/disk_usage_check.sh
sha1sum: 3cde181f47ec38652f9c8d9fc84bcd27b266ed8f

SubRepo (local) Info (low_disk-update-2020-09-11)
/home/lukeshirnia/development/github/git_rackspace/useful-scripts/low_disk/disk_usage_check.sh
sha1sum: 3cde181f47ec38652f9c8d9fc84bcd27b266ed8f

Verifying commit: sha1sums match!
low_disk-update-2020-09-11 (local branch) is inline with specified commit hash
------------------------------------------
```

### CODE REVIEW

**Comment by LukeHandle** [comment]
Fundamentally okay, though the BBCode seems inconsistent.

**Comment by LukeShirnia** [comment]
Fixed the inconsistent BBCode issues and updated the branch.
```
$ git branch
* low_disk-update-2020-09-11
[....]
$ ./audit.sh --update low_disk

------------------------------------------
Verifying recorded commit...

Commit on file: e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5
https://raw.githubusercontent.com/rackerlabs/useful-scripts/master/low_disk/.gitrepo

Remote Repo Info (commit)
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

SubRepo (remote) Info (master)
https://raw.githubusercontent.com/rackerlabs/useful-scripts/master/low_disk/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

Verifying commit: sha1sums match!
master (remote branch) is inline with specified commit hash
------------------------------------------

------------------------------------------
Checking if updates available... (script/commit vs script/master)

Remote 'Commit' URL
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

Remote 'Master' URL
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/master/disk_usage_check.sh
sha1sum: d01df8db02b9a7e99dc958e6d9096fd4a2cf132e

Master and commit hash do NOT match
Updates: Possible updates available

Compare URL:
https://github.com/LukeShirnia/Low_Disk/compare/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5...master

------------------------------------------

Branch Updated.....
Verifying Update.....
Cleaning up....
Deleted branch subrepo/low_disk (was 97cbd31).

------------------------------------------
Verifying recorded commit...

Commit on file: 97cbd31882a5d44a66b73dd4593b6096d02686a1
/home/lukeshirnia/development/github/git_rackspace/useful-scripts/low_disk/.gitrepo

Remote Repo Info (commit)
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/97cbd31882a5d44a66b73dd4593b6096d02686a1/disk_usage_check.sh
sha1sum: d01df8db02b9a7e99dc958e6d9096fd4a2cf132e

SubRepo (local) Info (low_disk-update-2020-09-11)
/home/lukeshirnia/development/github/git_rackspace/useful-scripts/low_disk/disk_usage_check.sh
sha1sum: d01df8db02b9a7e99dc958e6d9096fd4a2cf132e

Verifying commit: sha1sums match!
low_disk-update-2020-09-11 (local branch) is inline with specified commit hash
------------------------------------------
```

**Comment by LukeHandle** [comment]
Still inconsistent:

```
# bash disk_usage_check.sh -i -b


============================================================
 	 == / Filesystem Information ==
============================================================

Checking Inodes. Please note this could take a while to run...

============================================================
 	 == Server Time at start ==
============================================================

[code]
Fri Sep 18 09:43:41 UTC 2020
[/code]

============================================================
 	 == [b] Inode Information for [ / ] [/b] ==
============================================================

```

**Comment by LukeShirnia** [comment]
```
$ ./audit.sh --update low_disk

------------------------------------------
Verifying recorded commit...

Commit on file: e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5
https://raw.githubusercontent.com/rackerlabs/useful-scripts/master/low_disk/.gitrepo

Remote Repo Info (commit)
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

SubRepo (remote) Info (master)
https://raw.githubusercontent.com/rackerlabs/useful-scripts/master/low_disk/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

Verifying commit: sha1sums match!
master (remote branch) is inline with specified commit hash
------------------------------------------

------------------------------------------
Checking if updates available... (script/commit vs script/master)

Remote 'Commit' URL
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5/disk_usage_check.sh
sha1sum: 654c8ad2a144d7490f1d97b9401259d8cf1d7efe

Remote 'Master' URL
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/master/disk_usage_check.sh
sha1sum: eee0cff2d15d603d633b149f03c07a3e727da349

Master and commit hash do NOT match
Updates: Possible updates available

Compare URL:
https://github.com/LukeShirnia/Low_Disk/compare/e082e2d7b46a1c6ef4828f9d54524a387ec1c5c5...master

------------------------------------------

Branch Updated.....
Verifying Update.....
Cleaning up....
Deleted branch subrepo/low_disk (was 92dca87).

------------------------------------------
Verifying recorded commit...

Commit on file: 92dca879629f15891fc5a963f426fb1fcced1e7b
/home/lukeshirnia/development/github/git_rackspace/useful-scripts/low_disk/.gitrepo

Remote Repo Info (commit)
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/92dca879629f15891fc5a963f426fb1fcced1e7b/disk_usage_check.sh
sha1sum: eee0cff2d15d603d633b149f03c07a3e727da349

SubRepo (local) Info (low_disk-update-2020-09-11)
/home/lukeshirnia/development/github/git_rackspace/useful-scripts/low_disk/disk_usage_check.sh
sha1sum: eee0cff2d15d603d633b149f03c07a3e727da349

Verifying commit: sha1sums match!
low_disk-update-2020-09-11 (local branch) is inline with specified commit hash
------------------------------------------
```

**Review by LukeHandle — APPROVED** [review]

**Comment by LukeHandle** [comment]
./audit.sh --verify low_disk

------------------------------------------
Verifying recorded commit...

Commit on file: 92dca879629f15891fc5a963f426fb1fcced1e7b
https://raw.githubusercontent.com/rackerlabs/useful-scripts/low_disk-update-2020-09-11/low_disk/.gitrepo

\e[4mRemote Repo Info (commit)\e[24m
https://raw.githubusercontent.com/LukeShirnia/Low_Disk/92dca879629f15891fc5a963f426fb1fcced1e7b/disk_usage_check.sh
sha1sum: eee0cff2d15d603d633b149f03c07a3e727da349

\e[4mSubRepo (remote) Info (low_disk-update-2020-09-11)\e[24m
https://raw.githubusercontent.com/rackerlabs/useful-scripts/low_disk-update-2020-09-11/low_disk/disk_usage_check.sh
sha1sum: eee0cff2d15d603d633b149f03c07a3e727da349

Verifying commit: sha1sums match!
low_disk-update-2020-09-11 (remote branch) is inline with specified commit hash
------------------------------------------

**Pull request merged**
